export { default as DevOps } from "./DevOps";
export { default as HTML_CSS } from "./HTML_CSS";
export { default as Java } from "./Java";
export { default as JavaScript } from "./JavaScript";
export { default as Python } from "./Python";
export { default as ReactJS } from "./ReactJS";
export { default as Spring } from "./Spring";
export { default as Sql } from "./Sql";
export { default as Error } from "./Error";
export { default as Home } from "./Home";
export { default as MicroServices } from "./MicroServices";
export { default as FullStack } from "./FullStack";
export { default as Git } from "./Git";
export { default as Linux } from "./Linux";
export { default as Batch } from "./Batch";
export { default as Postman } from "./Postman";
export { default as Windows } from "./Windows";

export { default as Page_Creation } from "./Page_Creation";
