export { default as ArchitectureOptionsMain } from "./O0_ArchitecureOptionsSections/ArchitectureOptionsMain";
export { default as ServiceDiscoveryMain } from "./O1_ServiceDiscoverySections/ServiceDiscoveryMain";
export { default as APIGatewayMain } from "./O2_APIGatewaySections/APIGatewayMain";
export { default as ConfigManagementMain } from "./O3_ConfigManagementSections/ConfigManagementMain";
export { default as InterServiceCommMain } from "./O4_InterServiceCommSections/InterServiceCommMain";
export { default as LoadBalancingMain } from "./O5_LoadBalancingSections/LoadBalancingMain";
export { default as ResilienceFaultToleranceMain } from "./O6_ResilienceFaultToleranceSections/ResilienceFaultToleranceMain";
export { default as DistributedTracingMonitoringMain } from "./O7_DistributedTracingMonitoringSections/DistributedTracingMonitoringMain";
export { default as DataManagementMain } from "./O8_DataManagementSections/DataManagementMain";
